
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: teacherstudentmarks_development


test:
  <<: *default
  database: teacherstudentmarks_test

production:
  <<: *default
  database: teacherstudentmarks_production
  username: teacherstudentmarks
  password: <%= ENV['TEACHERSTUDENTMARKS_DATABASE_PASSWORD'] %>
